USE [master]
GO
/****** Object:  Database [Evalueacion]    Script Date: 02/28/2020 2:20:47 p. m. ******/
CREATE DATABASE [Evalueacion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Evalueacion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Evalueacion.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Evalueacion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Evalueacion_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Evalueacion] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Evalueacion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Evalueacion] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Evalueacion] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Evalueacion] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Evalueacion] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Evalueacion] SET ARITHABORT OFF 
GO
ALTER DATABASE [Evalueacion] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Evalueacion] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Evalueacion] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Evalueacion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Evalueacion] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Evalueacion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Evalueacion] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Evalueacion] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Evalueacion] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Evalueacion] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Evalueacion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Evalueacion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Evalueacion] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Evalueacion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Evalueacion] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Evalueacion] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Evalueacion] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Evalueacion] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Evalueacion] SET  MULTI_USER 
GO
ALTER DATABASE [Evalueacion] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Evalueacion] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Evalueacion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Evalueacion] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Evalueacion] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Evalueacion] SET QUERY_STORE = OFF
GO
USE [Evalueacion]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Evalueacion]
GO
/****** Object:  Table [dbo].[Empleado_Encuesta]    Script Date: 02/28/2020 2:20:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado_Encuesta](
	[Id_Empleado] [int] NOT NULL,
	[Id_Encuenta] [int] NOT NULL,
	[Id_Pregunta] [int] NOT NULL,
	[Respuesta] [varchar](100) NOT NULL,
	[Peso] [float] NOT NULL,
	[Fecha] [datetime] NOT NULL,
 CONSTRAINT [PK_Empleado_Encuesta] PRIMARY KEY CLUSTERED 
(
	[Id_Empleado] ASC,
	[Id_Encuenta] ASC,
	[Id_Pregunta] ASC,
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleados]    Script Date: 02/28/2020 2:20:49 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleados](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Apellido] [varchar](60) NOT NULL,
	[Nombre] [varchar](60) NOT NULL,
	[Sueldo] [float] NOT NULL,
	[Estado] [bit] NOT NULL,
	[Fecha_Ingreso] [datetime] NOT NULL,
 CONSTRAINT [PK_Empleados] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Encuestas]    Script Date: 02/28/2020 2:20:49 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Encuestas](
	[Id_Encuenta] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Fecha] [datetime] NOT NULL,
 CONSTRAINT [PK_Encuestas] PRIMARY KEY CLUSTERED 
(
	[Id_Encuenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Preguntas]    Script Date: 02/28/2020 2:20:50 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Preguntas](
	[Id_Pregunta] [int] IDENTITY(1,1) NOT NULL,
	[Id_Encuenta] [int] NOT NULL,
	[Pregunta] [varchar](100) NOT NULL,
	[Respuesta] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Preguntas] PRIMARY KEY CLUSTERED 
(
	[Id_Pregunta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Preguntas]  WITH CHECK ADD  CONSTRAINT [FK_Preguntas_Encuestas] FOREIGN KEY([Id_Encuenta])
REFERENCES [dbo].[Encuestas] ([Id_Encuenta])
GO
ALTER TABLE [dbo].[Preguntas] CHECK CONSTRAINT [FK_Preguntas_Encuestas]
GO
USE [master]
GO
ALTER DATABASE [Evalueacion] SET  READ_WRITE 
GO
